<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
  'BURL_TITLE' => 'Бизнес URLы (Короткие ссылки)',
  'MAIN_DESCRIPTION' => 'У вас есть реферальная ссылка или просто длинный урл? Создайте короткий урл с аналитикой...',
  'MAIN_KEYWORDS' => 'бизнесс, короткий, урл, аналитика, geo, рефер, платформа, браузер, клики',
  'LANG_CHANGED' => 'Язык успешно изменен',
  'ADD_URL' => 'Вставте свою длинную ссылку:',
  'DISABLE_SHORT_URL' => 'Срок действия короткой ссылки:',
  'TIME_NEVER_END' => 'Вечно',
  'TIME_ONE_WEEK' => 'Одна неделя',
  'TIME_ONE_MONTH' => 'Один месяц',
  'SHORTEN_URL' => 'Получить короткую ссылку',
  'SITE_STATISTICS' => 'Статистика:',
  'TOTAL_SU' => 'Всего ссылок',
  'TOTAL_UV' => 'Всего переходов',
  'NAVBAR_HOME' => 'Главная',
  'NAVBAR_LOGIN' => 'Вход',
  'NAVBAR_SIGNUP' => 'Регистрация',
  'NAVBAR_PROFILE' => 'Профиль',
  'NAVBAR_USERS' => 'Пользователи',
  'NAVBAR_RBAC' => 'RBAC',
  'NAVBAR_LOGOUT' => 'Выход',
  'CREATED_NEW_SHORT_URL' => 'Поздравляем! Вы успено создали новую короткую ссылку.',
  'YOUR_URLS' => 'Ваши ссылки',
  'LAST_PUBLIC_URLS' => 'Последние публичные ссылки',
  'ORIGINAL_URL' => 'Оригинальный урл',
  'CREATED' => 'Создано',
  'CLICKS' => 'Клики',
  'SHORT_URL' => 'Короткая ссылка',
  'ANALYTICS' => 'Аналитика',
  'YOU_DONT_HAVE_PRIVATE_URLS' => 'Вы еще не создали свой короткий урл',
  'ERROR_MSG' => 'Пожалуйста свяжитесь с администратором сайта, если постоянно получаете данную ошибку',
  'ENTER_VALID_SHORT_CODE' => 'Вы ввели не корректный короткий урл',
  'SHORT_CODE_NOT_FOUND' => 'Короткий урл не найден:',
  'SHORT_CODE_END_TIME' => 'Короткий урл отключен по истечению срока действия ',
  'SHORT_CODE_ERROR_URL' => 'Что-то не так с вашим УРЛ. Пожалуйста проверте корректность и доступность данного УРЛ. Статус запроса: ',
  'DETAIL_SHORT_CODE' => 'Аналитика для короткого урл - ',
  'EMPTY_ANALYTIC_REFERS' => 'Нет реферальных переходов',
  'REFER_URL' => 'Рефер URL',
  'REFER_COUNT' => 'Переходы',
  'ID' => 'ID',
  'USER_ID' => 'ID пользователя',
  'LONG_URL' => 'Длинная ссылка',
  'SHORT_CODE' => 'Короткий урл',
  'CREATED_TIME' => 'Дата создания',
  'TIME_END' => 'Дата окончания',
  'COUNTER' => 'Счетчик',
  'SHORT_URL_ID' => 'ID короткой ссылки',
  'USER_PLATFORM' => 'Платформа',
  'USER_AGENT' => 'Браузер',
  'USER_REFER' => 'Рефер',
  'USER_IP' => 'IP',
  'USER_COUNTRY' => 'Страна',
  'USER_CITY' => 'Город',
  'DATE' => 'Дата',
  'ALL_URLS' => 'Все ссылки',
  'UPDATE_SHORT_URL' => 'Обновить краткую ссылку',
];
