<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
  'BURL_TITLE' => 'Business URLs (Short urls)',
  'MAIN_DESCRIPTION' => 'If you have a long, cumbersome URL, you can "shorten" it. Create your short business url with analytics...',
  'MAIN_KEYWORDS' => 'business, short, URLs, analytics, geo, refer, platform, browser, clicks',
  'LANG_CHANGED' => 'Language successfully changed',
  'ADD_URL' => 'Paste your original URL here:',
  'DISABLE_SHORT_URL' => 'Disable short url?',
  'TIME_NEVER_END' => 'Never',
  'TIME_ONE_WEEK' => 'One week',
  'TIME_ONE_MONTH' => 'One month',
  'SHORTEN_URL' => 'Shorten URL',
  'SITE_STATISTICS' => 'Site statistics:',
  'TOTAL_SU' => 'Total Short Urls',
  'TOTAL_UV' => 'Total Url Visits',
  'NAVBAR_HOME' => 'Home',
  'NAVBAR_LOGIN' => 'Login',
  'NAVBAR_SIGNUP' => 'Signup',
  'NAVBAR_PROFILE' => 'Profile',
  'NAVBAR_USERS' => 'Users',
  'NAVBAR_RBAC' => 'RBAC',
  'NAVBAR_LOGOUT' => 'Logout',
  'CREATED_NEW_SHORT_URL' => 'Congratulation! You are created new short url.',
  'YOUR_URLS' => 'Your URLs',
  'LAST_PUBLIC_URLS' => 'The last public URLs',
  'ORIGINAL_URL' => 'Original url',
  'CREATED' => 'Created',
  'CLICKS' => 'Clicks',
  'SHORT_URL' => 'Short URL',
  'ANALYTICS' => 'Analytics',
  'YOU_DONT_HAVE_PRIVATE_URLS' => 'You don\'t have private urls',
  'ERROR_MSG' => 'Please contact us if you think this is a server error. Thank you.',
  'ENTER_VALID_SHORT_CODE' => 'Please enter valid short code',
  'SHORT_CODE_NOT_FOUND' => 'This short code not found:',
  'SHORT_CODE_END_TIME' => 'This short code was disabled by the end time ',
  'SHORT_CODE_ERROR_URL' => 'Something is wrong with your URL. Error: ',
  'DETAIL_SHORT_CODE' => 'Details for short code - ',
  'EMPTY_ANALYTIC_REFERS' => 'Empty refers url',
  'REFER_URL' => 'Refer url',
  'REFER_COUNT' => 'Count',
  'ID' => 'ID',
  'USER_ID' => 'User ID',
  'LONG_URL' => 'Long URL',
  'SHORT_CODE' => 'Short code',
  'CREATED_TIME' => 'Created time',
  'TIME_END' => 'Time end',
  'COUNTER' => 'Counter',
  'SHORT_URL_ID' => 'Short url ID',
  'USER_PLATFORM' => 'Platform',
  'USER_AGENT' => 'Browser',
  'USER_REFER' => 'Refer',
  'USER_IP' => 'IP',
  'USER_COUNTRY' => 'Country',
  'USER_CITY' => 'City',
  'DATE' => 'Date',
  'ALL_URLS' => 'All URLs',
  'UPDATE_SHORT_URL' => 'Update short url',
  'NOT_VALID_URL' => 'Not a valid URL',
];